### ISSUE TITLE
Add spinal cord segmentation and intervertebral disc levels to the template

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/template-dog#11]
Context: https://forum.spinalcordmri.org/t/integrating-dog-template/1179

In order to be used as a replacement to the PAM50 template, the dog template should come with:
- `templatedog_t1w.nii.gz`: The current T1w template
- `templatedog_t2w.nii.gz`: The current T2w template
- `templatedog_cord.nii.gz`: a spinal cord segmentation (equivalent to `PAM50_cord.nii.gz`)
- `templatedog_label_disc.nii.gz`: intervertebral discs (equivalent to `PAM50_label_disc.nii.gz`)
- `templatedog_levels.nii.gz`: spinal cord segmentation labeled for vertebral level (equivalent to `PAM50_levels.nii.gz`)
- `info_label.txt`: TXT file describing each file present in the template package. This file is used by `sct_register_to_template`

Once generated, these files should be packaged inside a `template` folder, and that folder should be enclosed into another folder called `templatedog`, and then zipped and uploaded as a release asset. See [latest PAM50 release](https://github.com/spinalcordtoolbox/PAM50/releases/tag/r20231024) for inspiration.

**Comment by rohanbanerjee** [comment]
I'm uploading the files for the template one by one. The below is the qc for the `templatedog_label_disc.nii.gz`
[qc_dog_template_disc_levels.zip](https://github.com/spinalcordtoolbox/template-dog/files/13673628/qc_dog_template_disc_levels.zip)

Uploading the other required files asap.

**Comment by rohanbanerjee** [comment]
Added all required files in the latest release (r20240112): https://github.com/spinalcordtoolbox/template-dog/releases/tag/v2.0

**Comment by jcohenadad** [comment]
@rohanbanerjee there were issues with your files #12 #13.

Next time you create a release, please consult with me before publishing the release.
