### ISSUE TITLE
New release r20240118 discussion

### ISSUE THREAD

**Issue by rohanbanerjee** [spinalcordtoolbox/template-dog#16]
After the previous release, I have updated the segmentation file, disc file (added a disc level) and the vertebrae level file (added a vertebrae level). I am attaching the folder in this issue as a zip folder (a gdrive link). If this looks good, I will publish the release with the release name `r20240118` with the same `r20240118` in the release tag.

https://drive.google.com/file/d/1UT2tqePQulXSopJwxAkpjdlytkewHT5e/view?usp=sharing

Discussion regarding registration using this is in the issue: https://github.com/spinalcordtoolbox/template-dog/issues/14

**Comment by jcohenadad** [comment]
![image](https://github.com/spinalcordtoolbox/template-dog/assets/2482071/4c6d0c16-bf82-4234-a7d4-f4db5b745ce5)

should not be here

**Comment by jcohenadad** [comment]
to remove:
![image](https://github.com/spinalcordtoolbox/template-dog/assets/2482071/b4ffd2da-718f-458a-b88e-e97124b685b4)

**Comment by jcohenadad** [comment]
![image](https://github.com/spinalcordtoolbox/template-dog/assets/2482071/072053d0-58fd-442a-a193-417dec7874fa)

**Comment by jcohenadad** [comment]
The cord segmentation is incorrect:

![image](https://github.com/spinalcordtoolbox/template-dog/assets/2482071/81be0e8c-8460-47d6-8fcf-5788545e8c54)

**Comment by jcohenadad** [comment]
cord seg should be symmetric-- see code in sct PR (if you don,t find it, ask @jcohenadad )

**Comment by jcohenadad** [comment]
Mismatch between t1 and t2. Consider re-doing the template:

![anim](https://github.com/spinalcordtoolbox/template-dog/assets/2482071/7dade11d-5707-45c8-adf4-dccf04089a7b)

**Comment by jcohenadad** [comment]
The cord seg is better done with starting from propseg on the t2 and then manually correct:

![image](https://github.com/spinalcordtoolbox/template-dog/assets/2482071/8149b98d-9842-4177-8435-5a21f02980ea)

**Comment by jcohenadad** [comment]
plan moving forward
- we ditch the t1w for now
- we re-do the seg on the t2w template

**Comment by rohanbanerjee** [comment]
Redone t2w template segmentation is part of the below link. If the cord segmentation looks good, it will be the next release.
`template dog_cord` = t2w template SC segmentation

https://drive.google.com/file/d/1IoKhUwCfpGDk9aPnA6htEF4RZUekocOE/view?usp=sharing

**Comment by jcohenadad** [comment]
Here is the result of registration of single dog image on the updated version of the template: [qc_templatedog_t2.zip](https://github.com/spinalcordtoolbox/template-dog/files/14065609/qc_templatedog_t2.zip)

As per https://github.com/spinalcordtoolbox/template-dog/issues/14#issuecomment-1901038707, here is the command used to produce this registration: 

~~~
# only keep 2 disc labels
sct_label_utils -i ~/data.neuro/template_dog_virginiatech/derivatives/labels/sub-HarshmanDobby/anat/sub-HarshmanDobby_T2_labels-disc.nii.gz -keep 4,10 -o labels_4-10.nii.gz
# run registration (params not optimized)
sct_register_to_template -i ~/data.neuro/template_dog_virginiatech/sub-HarshmanDobby/anat/sub-HarshmanDobby_T2.nii.gz -s ~/data.neuro/template_dog_virginiatech/derivatives/labels/sub-HarshmanDobby/anat/sub-HarshmanDobby_T2_label-centerline.nii.gz -ldisc labels_4-10.nii.gz -t . -c t2 -s-template-id 2 -ofolder test_discs4-10 -param step=1,type=seg,algo=centermass:step=2,type=im,algo=syn,metric=CC,iter=3 -qc qc~~~

SCT version used: Spinal Cord Toolbox (git-jca/4298-flow-d396ad3a9090900cc62d4b6eb4ccbc6d63d4a6eb)
~~~

**Comment by jcohenadad** [comment]
Information needed about how the new segmentation in https://github.com/spinalcordtoolbox/template-dog/issues/16#issuecomment-1911432122 was produced.

**Comment by rohanbanerjee** [comment]
This release `r20240118` has already been done and we are set to release the next version. Closing the issue therefore.
