### ISSUE TITLE
Lots of movements observed after the first round of the template generation

### ISSUE THREAD

**Issue by rohanbanerjee** [spinalcordtoolbox/template-dog#19]
### Some background info:
When the [generate_template pipeline](https://github.com/neuropoly/template/blob/master/generate_template.py) is run on the subjects. The below part describes for how many iterations and at what resolution should the pipeline run:
```
{'symmetric': True,
            'protocol': [{'iter': 5, 'level': 16},
                         {'iter': 5, 'level': 0.5}],
             'refine': True
}
``` 
The above pipeline will run for 5 iterations at a 2mm resolution and then 5 iterations at a 0.5mm resolution. 

### What is the issue:
When the pipeline runs, after each iteration, it gives the registered images to the template space for each subject. The observed issue is, after the 1st iteration, the output registered images show a lot of movement, like the below:

The below recording shows the 1st iteration image overlayed on top of the straightened image of the subject HarshmanDobby.

https://github.com/spinalcordtoolbox/template-dog/assets/25586344/c43259a0-be5c-4c2b-9986-10ec90222ce4

The below recording shows the 1st iteration image overlayed on top of the straightened image of the subject JamesMonk.

https://github.com/spinalcordtoolbox/template-dog/assets/25586344/f61e9a4b-0e27-4c71-a153-8a631a3e0778

This amount of movement is not expected since this is just the first iteration.

Next steps:
- [x] First guess is that this might be due to the resolutions set at the start of the iterations. Solution would be to try starting the iterations at a higher resolution (eg, 4mm or 2mm rather than 16mm) to help in better registration and hence less move.  
- [x] Second guess is that this might be due to different parameter in the `nist_mni_pipelines` package. Solution is to investigate the various parameters present in the `nist_mni_pipelines` which is imported in the [generate_template pipeline](https://github.com/neuropoly/template/blob/master/generate_template.py)

**Comment by rohanbanerjee** [comment]
> First guess is that this might be due to the resolutions set at the start of the iterations. Solution would be to try starting the iterations at a higher resolution (eg, 4mm or 2mm rather than 16mm) to help in better registration and hence less move.

I set the below the resolution,
```
{'symmetric': True,
            'protocol': [{'iter': 5, 'level': 2},
                         {'iter': 5, 'level': 1}],
             'refine': True
}
``` 
This did not improve the previous observation, the movements still persists.

**Comment by jcohenadad** [comment]
I suggest you use GIF between two images instead of MOV

**Comment by jcohenadad** [comment]
maybe consider using a mask for the registration?

**Comment by rohanbanerjee** [comment]
@rohanbanerjee TODO:
- [ ] Add GIF to show comparison

> First guess is that this might be due to the resolutions set at the start of the iterations. Solution would be to try starting the iterations at a higher resolution (eg, 4mm or 2mm rather than 16mm) to help in better registration and hence less move.

I set the below the resolution,
```
{'symmetric': True,
            'protocol': [{'iter': 1, 'level': 2},
                              {'iter': 3, 'level': 1}],
             'refine': True
}
``` 

**Why**
Starting from a even higher resolution like 2mm and more iterations at a higher resolution like 1mm drives the registration and template creation closer to how the subjects are, that is, less movements. The above experiment does reduce the movements observed significantly.

**Comment by rohanbanerjee** [comment]
- check whether linear or non-linear registration

**Comment by rohanbanerjee** [comment]
This issue has been solved by limiting the deformations by starting at a higher resolution as it was discussed below.

> Next steps:
> 
> * [x]  First guess is that this might be due to the resolutions set at the start of the iterations. Solution would be to try starting the iterations at a higher resolution (eg, 4mm or 2mm rather than 16mm) to help in better registration and hence less move.
