### ISSUE TITLE
Create a preliminary version of a dog template

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/template-dog#2]
- [x] [Stitch volumes together](https://github.com/sct-pipeline/template-dog/issues/1) (@joshuacwnewton)
- [x] Move the stitched files to project "duke:projects/template_dog_virginiatech" (@rohanbanerjee)
- [x] Segment spinal cord (@rohanbanerjee)
- [x] Run template creation pipeline. Re-use code from https://github.com/sct-pipeline/exvivo-template (@rohanbanerjee)

**Comment by rohanbanerjee** [comment]
Preliminary version of the template has been created. Closing this issue for now. Can be reopened if required.
