### ISSUE TITLE
Upload all the dog data to git-annex

### ISSUE THREAD

**Issue by rohanbanerjee** [spinalcordtoolbox/template-dog#3]
All the dog data present at `duke/temp/rohan/bids_data` to `git-annex`

**Comment by rohanbanerjee** [comment]
**Repository name:** template_dog_virginiatech
**Upload branch name:** rb/data_upload
It contains all the stitched images and derivatives like centerline and discs.
**Missing:** Dataset details like dataset_description –> subject details.

**Comment by jcohenadad** [comment]
Please create a specific issue on https://github.com/neuropoly/data-management/issues with a new label and cross-ref the issue here and there-- thanks

**Comment by rohanbanerjee** [comment]
Related issue in the [https://github.com/neuropoly/data-management](https://github.com/neuropoly/data-management/issues) repo: https://github.com/neuropoly/data-management/issues/269

**Comment by jcohenadad** [comment]
once done update readme

**Comment by jcohenadad** [comment]
@rohanbanerjee needs some update

**Comment by rohanbanerjee** [comment]
The data has been uploaded and going through final iterations here: https://github.com/neuropoly/data-management/issues/269. Closing this issue therefore.
