### ISSUE TITLE
Re-draw the SC centerline for a better template

### ISSUE THREAD

**Issue by rohanbanerjee** [spinalcordtoolbox/template-dog#7]
### Context:
After the template for the `T2` contrast was generated, we observed that the there is a small curve in the final template which looks like the below:
<img width="86" alt="Screen Shot 2023-10-02 at 11 39 19 AM" src="https://github.com/spinalcordtoolbox/template-dog/assets/25586344/d38370ac-dd9e-4769-8392-bf0b8afa4186">

After a discussion with @benjamindeleener, we found out that it is due to the centerline being outside the spinal cord in 2 out of 5 subjects. 

### Next steps:
I will manually re-draw the centrelines to solve the above mentioned issue and also remove the minor oscillations in the centerline.

**Comment by rohanbanerjee** [comment]
I re-drew the mask for 2 out of the 5 subjects. The small curve in the template is now gone. The T2 (N=5) after 9 iterations looks like the below:

<img width="90" alt="Screen Shot 2023-10-04 at 12 32 11 AM" src="https://github.com/spinalcordtoolbox/template-dog/assets/25586344/517d6539-d57c-4e49-85c8-5181bc984e22">

The error in the issue seems to be solved now.

**Comment by jcohenadad** [comment]
Were the centerlines pushed on git-annex?

**Comment by rohanbanerjee** [comment]
Issue opened here: https://github.com/spinalcordtoolbox/template-dog/issues/3
