### ISSUE TITLE
Strange overlay of different image intensities

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/template-dog#8]
results from 2023-10-04:

<img width="433" alt="image" src="https://github.com/spinalcordtoolbox/template-dog/assets/2482071/20592261-8d04-4d0f-974d-764126f6d337">

Figure out:
- why there are the zeroed voxels on the side (RL)-- maybe more aggressive cropping needed
- how come there seem to be different image intensities across subjects, and one (or more) subjects seem to have a smaller FOV

**Comment by jcohenadad** [comment]
My suggestion to create the template is to crop out that weird region, but only if it is not _too close_ to the spinal cord. If cropping it too aggressive, then it's fine, let's have a template with these weird intensities on the side.

**Comment by rohanbanerjee** [comment]
- Reply from our collaborator, Dr. Shinn on this issue over mail correspondence: "Unfortunately I do not but it was a constant issue nobody was ever able to fix". 
- Removed the zeroed voxels by more aggressive cropping. If the uneven intensities have to be removed then the cropping gets too close to the spinal cord as a result the uneven intensities will be a part of the template but the zeroed voxels are removed.

**Comment by rohanbanerjee** [comment]
The template slice looks like the below now.
<img width="418" alt="Screenshot 2023-11-23 at 3 26 36 AM" src="https://github.com/spinalcordtoolbox/template-dog/assets/25586344/0ac93e79-d825-474b-ba2d-0ebe4ec1d213">
