### ISSUE TITLE
Dog data missing subject wise information

### ISSUE THREAD

**Issue by rohanbanerjee** [spinalcordtoolbox/template-dog#9]
Opening this issue to discuss ways to get the description/information of the subjects in the `virginiatech` dog data. This would be used to update the data on git-annex. 

Related issue: https://github.com/spinalcordtoolbox/template-dog/issues/3#issue-1914133043, https://github.com/neuropoly/data-management/issues/269#issue-1940137858

**Comment by jcohenadad** [comment]
What information is missing?

**Comment by rohanbanerjee** [comment]
The demographic information of the dog data is missing. I cannot fill the fields in `dataset_description.json` in the dog data.

**Comment by jcohenadad** [comment]
Could you ask our collaborator? you were on the email thread with him

**Comment by rohanbanerjee** [comment]
This has been done https://github.com/neuropoly/data-management/issues/269. Closing this issue.
